### ISSUE TITLE
Runtime Error diamond-hands.js

### ISSUE THREAD

**Issue by steini225** [chrisrabe/bitburner-automation#26]
RUNTIME ERROR
diamond-hands.js@home (PID - 60093)

getPosition: Invalid stock symbol: ECP

Stack:
diamond-hands.js:L12@getStonks
diamond-hands.js:L92@Module.main

**Comment by lnagler1** [comment]
When do you get this Error, right after running or after some time?

**Comment by steini225** [comment]
right after running. 
looks like there are some issues because some things got changes at gameupdates

**Comment by Zerris** [comment]
ns.stock.buy and ns.stock.sell got depreciated and replaced in the game. To get your copy of the script running just replace the .buy with .buyStock and .sell with .sellStock.

**Comment by chrisrabe** [comment]
PR merged. Should work now 👍 Thanks @Zerris

**Comment by iLagProductions** [comment]
Just out of curiosity with the recent update to v2.1.0 did this cause another issue to bring this run time error back? I am by no means an expert programmer but I do understand what this script is doing. I read the changes and comments by Zerris and everything seems to be the way it should. I tried rolling back the code to prior iterations and still no luck.

`RUNTIME ERROR
diamond-hands.js@home (PID - 167)

getPosition: Invalid stock symbol: ECP

Stack:
diamond-hands.js:L12@getStonks
diamond-hands.js:L92@Module.main`
